#!/bin/bash

silent() {
  if [ "$3" = "--debug" ];  then
    "$@"
  else
    "$@" > /dev/null 2>&1
  fi
}

if [ ! -n "$2" ]; then
    echo $"Usage:"
    echo "  $0 {install|remove|update} {packagename}"
    echo "  $0 {install|remove|update} {packagename} --debug"
    echo "  $0 -h|--help"
    exit 1
fi

if [ "$3" = "--debug" ]; then
  set -x
fi

init() {
    mkdir -p /www/html/extensions/.cache
    cd /www/html
}

cleanup() {
    echo "**** [flarum-extension-tool] Cleaning up"
    silent php /www/html/flarum cache:clear
    chown -R nginx:www-data /www/html
    chown -R nginx:www-data /data
    rm -rf /tmp/composer-updates
}

check_if_installed() {
    cat /www/html/composer.json | grep $1 -c
}


case "$1" in
  install|i) # Install Package
    init
    echo "**** [flarum-extension-tool] Installing Package ${2}"
    if [ `check_if_installed $2` != "0" ] ; then
        echo "**** [flarum-extension-tool] ${2} is already installed. Perhaps you wish to update?"
    else
        silent composer require ${2}
        echo "**** [flarum-extension-tool] ${2} installed."
    fi
    cleanup
    ;;
  remove|delete|r|d) # Remove Package
    init
    echo "**** [flarum-extension-tool] Removing Packge ${2}"
    if [ `check_if_installed $2` != "0" ] ; then
        silent composer remove ${2}
        echo "**** [flarum-extension-tool] ${2} removed."
    else
        echo "**** [flarum-extension-tool] ${2} not installed. Please verify package name"
    fi
    cleanup
    ;;
  update|u)  # Update Package
    init
    if [ `check_if_installed $2` != "0" ] ; then
        echo "**** [flarum-extension-tool] Updating Package ${2}"
        echo "**** [flarum-extension-tool] Downloading Repository Information"
        silent composer outdated > /tmp/composer-updates
           if [[ `cat /tmp/composer-updates | grep ${2} | awk '{print $1'}` ]]; then
                   if [ `cat /tmp/composer-updates | grep ${2} | awk '{print $2'}` != `cat /tmp/composer-updates | grep ${2} | awk '{print $4'}` ]; then    
                echo "**** [flarum-extension-tool] Newer version of ${2} found. Upgrading.."
                    silent composer update ${2}
                    silent php /www/html/flarum migrate
                    echo "**** [flarum-extension-tool] Update of package ${2} completed."
                   fi
           else
           echo "**** [flarum-extension-tool] No update required for ${2}"
               fi
    fi
    cleanup
    ;;
  --help|-h)
    echo "Flarum Docker Extension Tool"
    echo $"Usage:"
    echo "  $0 {install|remove|update} {packagename}"
    echo
    echo "  install             Install Package if not already installed"
    echo "  remove              Remove Package if installed"
    echo "  update              Updte Package if installed"
    ;;
  *)
    echo $"Usage:"
    echo "  $0 {install|remove|update} {packagename}"
    echo "  $0 {install|remove|update} {packagename} --debug"
    echo "  $0 -h|--help"
    exit 1
esac