#!/usr/bin/with-contenv bash

### Set Debug Mode
if [ "$DEBUG_MODE" = "TRUE" ] || [ "$DEBUG_MODE" = "true" ]; then
    DEBUG_MODE=true
else
    DEBUG_MODE=false
fi
 
ADMIN_EMAIL=${ADMIN_EMAIL:-"admin@example.com"}
ADMIN_PASS=${ADMIN_PASS:-"flarum"}
ADMIN_PATH=${ADMIN_PATH:-"admin"}
ADMIN_USER=${ADMIN_USER:-"admin"}
API_PATH=${API_PATH:-"api"}
DB_PORT=${DB_PORT:-3306}
DB_PREFIX=${DB_PREFIX:-"flarum_"}
SITE_TITLE=${SITE_TITLE:-"Flarum"}
