version: '2.4'
services:

  flarum-app:
    image: tiredofit/flarum
    container_name: flarum-app
    labels:
      - traefik.enable=true
      - traefik.http.routers.flarum.rule=Host(`flarum.example.com`)
      - traefik.http.services.flarum.loadbalancer.server.port=80
    links:
      - flarum-db
    volumes:
      - ./data:/data
      - ./logs/:/www/logs
    environment:
      - TIMEZONE=America/Vancouver
      - CONTAINER_NAME=flarum-app

      - ADMIN_USER=admin
      - ADMIN_PASS=flarum
      - ADMIN_EMAIL=admin@example.com

      - SITE_TITLE=Flarum
      - SITE_URL=https://flarum.example.com

      - DB_HOST=flarum-db
      - DB_NAME=flarum
      - DB_USER=flarum
      - DB_PASS=flarum

    networks:
      - proxy
      - services
    restart: always

  flarum-db:
    image: tiredofit/mariadb:10.8-latest
    container_name: flarum-db
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - TIMEZONE=America/Vancouver
      - CONTAINER_NAME=flarum-db
      - ROOT_PASS=password
      - DB_NAME=flarum
      - DB_USER=flarum
      - DB_PASS=flarum


    networks:
      - services
    restart: always

  flarum-db-backup:
    container_name: flarum-db-backup
    image: tiredofit/db-backup
    links:
     - flarum-db
    volumes:
      - ./dbbackup:/backup
    environment:
      - TIMEZONE=America/Vancouver
      - CONTAINER_NAME=flarum-db-backup
      - DB_HOST=flarum-db
      - DB_TYPE=mariadb
      - DB_NAME=flarum
      - DB_USER=flarum
      - DB_PASS=flarum
      - DB01_BACKUP_INTERVAL=1440
      - DB01_BACKUP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
    networks:
      - services
    restart: always

networks:
  proxy:
    external: true
  services:
    external: true
