version: '3.7'
services:
  
  flarum-app:
    image: tiredofit/flarum
    container_name: flarum-app
    labels:
      - traefik.enable=true
      - traefik.public.backend=flarum-app
      - traefik.public.port=80
      - traefik.public.frontend.rule=Host:flarum.example.com
      - traefik.docker.network=proxy
    links:
      - flarum-db
    volumes:
      - ./data:/data
      - ./logs/:/www/logs
    environment:
      - CONTAINER_NAME=flarum-app

      - ADMIN_USER=admin
      - ADMIN_PASS=flarum
      - ADMIN_EMAIL=admin@example.com

      - SITE_TITLE=Flarum
      - SITE_URL=https://flarum.example.com
  
      - DB_HOST=flarum-db
      - DB_NAME=flarum
      - DB_USER=flarum
      - DB_PASS=flarum

      - DEBUG_MODE=FALSE
    networks:
      - proxy
      - services
    restart: always

  flarum-db:
    image: tiredofit/mariadb
    container_name: flarum-db
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - ROOT_PASS=password
      - DB_NAME=flarum
      - DB_USER=flarum
      - DB_PASS=flarum

      - CONTAINER_NAME=flarum-db
    networks:
      - services
    restart: always

  flarum-db-backup:
    container_name: flarum-db-backup
    image: tiredofit/db-backup
    links:
     - flarum-db
    volumes:
      - ./dbbackup:/backup
    environment:
      - CONTAINER_NAME=flarum-db-backup
      - DB_HOST=flarum-db
      - DB_TYPE=mariadb
      - DB_NAME=flarum
      - DB_USER=flarum
      - DB_PASS=flarum
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
      - COMPRESSION=BZ
      - MD5=TRUE
    networks:
      - services
    restart: always

networks:
  proxy:
    external: true
  services:
    external: true
